### ISSUE TITLE
Edge Detection

### ISSUE THREAD

**Issue by jonasbarth** [jonasbarth/fds-2022-final-project#1]
# What?
* use edge detection for classifying image patches 

# How?
1. Detect edges in all image patches by using various edge detection mechanisms.
2. Pass patches with edges through a classifier (e.g. Logistic Regression)
3. Train classifier
4. Evaluate

**Comment by Mamiglia** [comment]
I found that there is this library that computes the histogram of gradients for us: https://scikit-image.org/docs/stable/auto_examples/features_detection/plot_hog.html
I think this might be useful

**Comment by jonasbarth** [comment]
So really, edge detection + histograms is part of the same classification pipeline, right? So we would just have:

1. Edge detection with histogram of oriented gradients and classify
2. Use CNN to classify

Right?

**Comment by jonasbarth** [comment]
I added a small HOG example to the notebook, taken from the scikit link you posted. https://github.com/jonasbarth/fds-2022-final-project/blob/07277714ecc38b8f1d1d6c27a52d5f88cb92ef04/edge_detection_test.ipynb

**Comment by Mamiglia** [comment]
> edge detection + histograms is part of the same classification pipeline

Yes, I would say so

**Comment by jonasbarth** [comment]
# TODO
* research how classification can be done using colour histograms
* look into binning gradients from our HOG (similar to what we did in the colour histograms) and then find the closest image.

**Comment by jonasbarth** [comment]
# Classification Using HOG
* this guy uses a KNN for classifying images using a HOG https://medium.com/swlh/histogram-of-oriented-gradients-hog-for-multiclass-image-classification-and-image-recommendation-cf0ea2caaae8
* HOG + KNN https://www.kaggle.com/code/anirbanmalick/image-classification-using-hog-knn-98-acc/notebook
* HOG + KNN + SVM for Tuberculosis x-rays https://ieeexplore.ieee.org/document/9590186
* matlab example using HOG + SVM https://it.mathworks.com/help/vision/ug/digit-classification-using-hog-features.html
* paper using HOG + SVM for digit classification https://ieeexplore.ieee.org/document/9823782

After a quick google search, it seems that most people seem to be using SVM or KNN. If we decide between these two, I would go for the **KNN** since that is one we covered in class.
