### ISSUE TITLE
Colours Histogram (KNN etc.)

### ISSUE THREAD

**Issue by jonasbarth** [jonasbarth/fds-2022-final-project#6]
# What we want to do?
Create colours histograms and use as input to a classifier, starting with KNN.

# How

## Preprocessing
The goal of the preprocessing is to create a `Pipeline` object that we can reuse when using the test data.
1. Load data
2. Decide how many bins we want per channel. 
3. Create histogram using `scikit-learn`
4. Potentially save histograms (check if pipeline is fast)

## Evaluation
1. Apply pipeline to test data
2. Get scores for test data
3. Select different features (channels) and retry

## Visualisations
Somehow show the scores of the model. Maybe use the same plot as in the paper
![image](https://user-images.githubusercontent.com/32641360/206516872-621ac121-393e-4c87-a4fa-d02f9f0405e5.png)

**Comment by Mamiglia** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/33762284/207459430-b2396c92-6596-4ade-ab21-c4208707188e.png">
It's confirmed that we will have to solve this problem of some images being normalized and some not.
Possible approaches:
- Find the original mean and std dev that were used in the original paper and use them to normalize the new unnormalized patches
- Make an estimation of mean and std for each channel and normalize based on it, warning: we may normalize things in different ways

**Comment by Mamiglia** [comment]
Ok, turns out that the file `stats_train.json` already contains the means and standard deviations for each channel, so we're safe!

```json
{"means": [151.98861694335938, 141.67233276367188, 147.73736572265625, 126.35386657714844, 41.389190673828125, 86.37078094482422, 54.272972106933594, 34.75004959106445, 129.8513641357422, 1297.374755859375, -0.09093914926052094, -0.534999668598175, 0.4840894341468811, 5337.916015625, 26.90826988220215], "stds": [85.87097930908203, 89.88019561767578, 88.11711883544922, 79.6325454711914, 33.70036697387695, 21.227155685424805, 36.88022232055664, 30.684616088867188, 86.3227310180664, 466.8656311035156, 0.11548927426338196, 0.35953786969184875, 0.32466045022010803, 826.7803955078125, 14.102063179016113]}
```

**Comment by Mamiglia** [comment]
<img width="461" alt="Screenshot_20221214_165423" src="https://user-images.githubusercontent.com/33762284/207644334-d91083ba-7912-44ae-9004-9d1bc5980062.png">
Guys...

The results are awesome <3

**Comment by jonasbarth** [comment]
God damn that's so beautiful 😍 very cool results!!!

**Comment by MattiaCastaldo** [comment]
![Screenshot 2022-12-14 at 23-15-33 hoc - Jupyter Notebook](https://user-images.githubusercontent.com/113530191/207726881-523c200f-13e4-4581-be85-720d6650b76b.png)

Here we got the best result with Logistic Regression, selcting all channels and the median as inputer. (accuracy = 98%)
