### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by Mamiglia** [jonasbarth/fds-2022-final-project#8]
[LINK](https://docs.google.com/presentation/d/1WMq6boamqTwwUekdVn4A7VmaPeCc4xNKfiRQqd0eK2U/edit#slide=id.p)

For the final presentation me and Mattia were thinking about making 2 'general' slides and 3 specific ones (one for each approach)

So it would be something like:
1. Introduction : visualization of dataset  and preprocessing 
2. Histogram of Gradients
3. Histogram of Colors
4. CNN
5. Conclusion and performance comparison

In particular I was thinking to add this images to slide 1, in order to have them visualize the slices and channels:
![image](https://user-images.githubusercontent.com/33762284/208236891-02a4f079-7b72-474b-89df-2602714da33a.png)
![image](https://user-images.githubusercontent.com/33762284/208236894-0b10b0a2-6e9e-47e7-afd6-ce209bdad5d2.png)

And to the last one this in order to compare performances:
![image](https://user-images.githubusercontent.com/33762284/208236937-4f5c42a8-ebbb-4f30-8184-268cac5e3f94.png)

**Comment by Mamiglia** [comment]
For slide n.5 we need the outputs of your approach in this format:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/33762284/208237046-061316ec-f432-4547-9d6c-d00feb0f8051.png">

**Comment by jonasbarth** [comment]
> [LINK](https://docs.google.com/presentation/d/1WMq6boamqTwwUekdVn4A7VmaPeCc4xNKfiRQqd0eK2U/edit#slide=id.p)
> 
> For the final presentation me and Mattia were thinking about making 2 'general' slides and 3 specific ones (one for each approach)
> 
> So it would be something like:
> 
> 1. Introduction : visualization of dataset  and preprocessing
> 2. Histogram of Gradients
> 3. Histogram of Colors
> 4. CNN
> 5. Conclusion and performance comparison
> 
> In particular I was thinking to add this images to slide 1, in order to have them visualize the slices and channels: ![image](https://user-images.githubusercontent.com/33762284/208236891-02a4f079-7b72-474b-89df-2602714da33a.png) ![image](https://user-images.githubusercontent.com/33762284/208236894-0b10b0a2-6e9e-47e7-afd6-ce209bdad5d2.png)
> 
> And to the last one this in order to compare performances: ![image](https://user-images.githubusercontent.com/33762284/208236937-4f5c42a8-ebbb-4f30-8184-268cac5e3f94.png)

Yes that's a great idea! 

So we will also do channels 5,4,2? And do you have the code for creating this diagram?

**Comment by Mamiglia** [comment]
I thought that we always said to do also 5-4-2 no? But in nay case np, it's not important to do also that, if it's too late we will skip it

**Comment by Mamiglia** [comment]
For the last diagram we just need you to pass us your results in this shape as a pandas dataframe:


> For slide n.5 we need the outputs of your approach in this format: <img alt="image" width="264" src="https://user-images.githubusercontent.com/33762284/208237046-061316ec-f432-4547-9d6c-d00feb0f8051.png">


So we can merge all the results together in one plot like this one: 
![immagine](https://user-images.githubusercontent.com/33762284/208250950-ce19cba0-34df-4639-8a45-506f0cdd2aa0.png)

**Comment by jonasbarth** [comment]
> I thought that we always said to do also 5-4-2 no? But in nay case np, it's not important to do also that, if it's too late we will skip it

I was just curious because I thought we said RGB; 6,7,8; 11, 12, 13 😁 but I have the results for 2-4-5 so it's not a problem. Do you want the actual dataframe or just a screenshot? Because that looks like some sort of group by logic that I have to recreate.

**Comment by jonasbarth** [comment]
Also, should be write it like 6,7,8 instead of 6-8? Because 5-4-2 means 5,4,2 and not 5,4,3,2 right? Otherwise we would be mixing two styles.

**Comment by Mamiglia** [comment]
For legacy reasons I would keep 6-8 event though it means 6-7-8.

**Comment by Mamiglia** [comment]
> > I thought that we always said to do also 5-4-2 no? But in nay case np, it's not important to do also that, if it's too late we will skip it
> 
> I was just curious because I thought we said RGB; 6,7,8; 11, 12, 13 😁 but I have the results for 2-4-5 so it's not a problem. Do you want the actual dataframe or just a screenshot? Because that looks like some sort of group by logic that I have to recreate.

The dataframe would be better, possibly in csv format. Also there's no need to recreate the indexes as they are there, you can also pass it in this other shape and we will take care of it:
![immagine](https://user-images.githubusercontent.com/33762284/208251718-70c5766e-6445-4fa1-81f4-c66ac69417d2.png)

**Comment by jonasbarth** [comment]
> > > I thought that we always said to do also 5-4-2 no? But in nay case np, it's not important to do also that, if it's too late we will skip it
> > 
> > 
> > I was just curious because I thought we said RGB; 6,7,8; 11, 12, 13 😁 but I have the results for 2-4-5 so it's not a problem. Do you want the actual dataframe or just a screenshot? Because that looks like some sort of group by logic that I have to recreate.
> 
> The dataframe would be better, possibly in csv format. Also there's no need to recreate the indexes as they are there, you can also pass it in this other shape and we will take care of it: ![immagine](https://user-images.githubusercontent.com/33762284/208251718-70c5766e-6445-4fa1-81f4-c66ac69417d2.png)

Ok, then I will send a csv. For the metrics, did you use sklearn's `precision_recall_fscore_support`? If so, what was the `average` parameter value you used? Because we need to do some averaging across classes.

**Comment by jonasbarth** [comment]
@Mamiglia here are the metrics, with the score being the weighted average across classes.
[knn_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10252182/knn_metrics.csv)

**Comment by Mamiglia** [comment]
Thanks! but didn't you do also logistic regression?

Also this is not crucially important but our wasn't the average score but the maximum. Sorry for not specifying this earlier.

**Comment by jonasbarth** [comment]
Javi was still working on log reg I believe. Ok I will use the max and resend it.

**Comment by jonasbarth** [comment]
> For legacy reasons I would keep 6-8 event though it means 6-7-8.

We can do that, but if we want to compare it to the paper, then I don't think it actually makes sense do the analysis on the channels 6-7-8, but only channels 6 and 8? I mean either 6-8 means 6,7,8 or just 6 and 8. From the paper it seems that it just means channel 6 and 8 actually. 

Because I would actually be confused if 6-8 means 6,7,8 but 5-4-2 means 5,4,2. I wouldn't be able to explain that 🤷‍♂️ 😁

**Comment by jonasbarth** [comment]
Here are the metrics with the max [knn_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10252249/knn_metrics.csv)

**Comment by Mamiglia** [comment]
> > For legacy reasons I would keep 6-8 event though it means 6-7-8.
> 
> We can do that, but if we want to compare it to the paper, then I don't think it actually makes sense do the analysis on the channels 6-7-8, but only channels 6 and 8? I mean either 6-8 means 6,7,8 or just 6 and 8. From the paper it seems that it just means channel 6 and 8 actually.
> 
> Because I would actually be confused if 6-8 means 6,7,8 but 5-4-2 means 5,4,2. I wouldn't be able to explain that 🤷‍♂️ 😁

Ok then if also @nem-42098 is okay with it let's go for it

**Comment by jonasbarth** [comment]
> > > For legacy reasons I would keep 6-8 event though it means 6-7-8.
> > 
> > 
> > We can do that, but if we want to compare it to the paper, then I don't think it actually makes sense do the analysis on the channels 6-7-8, but only channels 6 and 8? I mean either 6-8 means 6,7,8 or just 6 and 8. From the paper it seems that it just means channel 6 and 8 actually.
> > Because I would actually be confused if 6-8 means 6,7,8 but 5-4-2 means 5,4,2. I wouldn't be able to explain that 🤷‍♂️ 😁
> 
> Ok then if also @nem-42098 is okay with it let's go for it

Just to clarify, to only do 6 and 8 instead of 6,7,8? 😀

**Comment by Mamiglia** [comment]
Nono, to call it 6-7-8 rather than 6-8. I think Nemish needs always exactly 3 layers for CNN.

**Comment by jonasbarth** [comment]
Ok, makes sense! Sorry for the confusion. Here is the LR data:

[hog_lr_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10252321/hog_lr_metrics.csv)
Edit: had to update the column names to match yours

**Comment by MattiaCastaldo** [comment]
@jonasbarth  Is this the correct DataFrame of your performances (HOG)?

![image](https://user-images.githubusercontent.com/113530191/208266722-d7e22615-ded3-4b61-9281-a77e17ad49de.png)

The final diagram should be like this 
![Screenshot_20221217_223214](https://user-images.githubusercontent.com/113530191/208266735-3deb0da8-3e76-4bcc-beb7-6040e2b244fd.png)

@nem-42098 performances remains to be included
Let me know what you think about it

**Comment by nem-42098** [comment]
Here are the results for the CNN-VGG 16 network. Apologies for the delay. 
[CNN_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10253542/CNN_metrics.csv)

**Comment by jonasbarth** [comment]
> @jonasbarth Is this the correct DataFrame of your performances (HOG)?
> 
> ![image](https://user-images.githubusercontent.com/113530191/208266722-d7e22615-ded3-4b61-9281-a77e17ad49de.png)
> 
> The final diagram should be like this ![Screenshot_20221217_223214](https://user-images.githubusercontent.com/113530191/208266735-3deb0da8-3e76-4bcc-beb7-6040e2b244fd.png)
> 
> @nem-42098 performances remains to be included Let me know what you think about it

Yes, looks correct!

**Comment by jonasbarth** [comment]
@MattiaCastaldo here is the final csv:
[hog_knn_lr_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10254122/hog_knn_lr_metrics.csv)

**Comment by jonasbarth** [comment]
@MattiaCastaldo [hog_knn_lr_metrics.csv](https://github.com/jonasbarth/fds-2022-final-project/files/10254149/hog_knn_lr_metrics.csv)
